server:
  port: 8090

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
      routes:
        - id: ms-authentication
          uri: http://localhost:8091
          predicates:
            - Path=/api/auth/**
        - id: ms-wallet
          uri: lb://ms-wallet
          predicates:
            - Path=/api/wallet/**
          filters:
            - AutorizacionFilter
        - id: ms-sendmail
          uri: lb://ms-sendmail
          predicates:
            - Path=/api/sendmail/**

auth:
  uri: http://ms-authentication:8091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true