server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: ms-authentication-container
          uri: lb://ms-authentication-container
          predicates:
            - Path=/api/auth/**
        - id: ms-wallet
          uri: lb://ms-wallet
          predicates:
            - Path=/api/wallet/**
          filters:
            - AutorizacionFilter
        - id: ms-sendmail
          uri: lb://ms-sendmail
          predicates:
            - Path=/api/sendmail/**

auth:
  url: http://20.75.145.21

eureka:
  client:
    service-url:
      defaultZone: http://service-registry-container:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true