server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: ms-authentication
          uri: lb://ms-authentication
          predicates:
            - Path=/api/auth/**
        - id: ms-wallet
          uri: lb://ms-wallet
          predicates:
            - Path=/api/wallet/**
          # filters:
          #   - AutorizacionFilter
            
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true