server:
  port: 8090

spring:
  cloud:
    gateway:
      cors:
        enabled: true
        allow-credentials: true
        allowed-origins: "*"
        allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
        allowed-headers: "*"
        exposed-headers: "Authorization"
        max-age: 3600
      routes:
        - id: ms-authentication
          uri: lb://ms-authentication
          predicates:
            - Path=/api/auth/**
        - id: ms-wallet
          uri: lb://ms-wallet
          predicates:
            - Path=/api/wallet/**
          filters:
            - AutorizacionFilter
        - id: ms-sendmail
          uri: lb://ms-sendmail
          predicates:
            - Path=/api/sendmail/**

auth:
  uri: http://localhost:8091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true