server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: ms-authentication
          uri: lb://ms-authentication
          predicates:
            - Path=/api/auth/**
        - id: ms-client
          uri: lb://ms-client
          predicates:
            - Path=/api/clients/**
          filters:
            - AutorizacionFilter
        - id: ms-account
          uri: lb://ms-account
          predicates:
            - Path=/api/accounts/**
          filters:
            - AutorizacionFilter
        - id: ms-transaction
          uri: lb://ms-transaction
          predicates:
            - Path=/api/transactions/**
          filters:
            - AutorizacionFilter
            
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true