server:
  port: 8091

spring:
  data:
    mongodb:
      uri: mongodb://wcspservice:FuRpYY1wsSkVGNpR@ac-hpdsx2q-shard-00-00.6fecff2.mongodb.net:27017,ac-hpdsx2q-shard-00-01.6fecff2.mongodb.net:27017,ac-hpdsx2q-shard-00-02.6fecff2.mongodb.net:27017/?replicaSet=atlas-12h4j2-shard-0&ssl=true&authSource=admin
      database: bank
  jackson:
    serialization:
      fail-on-empty-beans: 'false'

jwt:
  secret: secret

eureka:
  client:
    service-url:
      defaultZone: http://service-registry-container:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true